---
title:  "mecab 설치할 때 발생하는 에러"
excerpt: ""
toc: true
toc_sticky: true

categories:
  - mecab
tags:
  - mecab
last_modified_at: 2022-05-21-08:00
---

<br>
<br>

[python-mecab-ko](https://github.com/jonghwanhyeon/python-mecab-ko)를 설치하는 방법은 다음과 같다.

```bash
pip install python-mecab-ko

또는

conda install -c conda-forge mecab-ko  
```

<br>
<br>

설치하고 다음과 같이 실행하면 에러가 발생한다.

<br>

```python
import mecab
mecab = mecab.MeCab()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/ipykernel_31265/2337645710.py in <module>
      1 import mecab
----> 2 mecab = mecab.MeCab()

~/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/mecab/mecab.py in __init__(self, dicpath)
     51             argument = '-d %s' % dicpath
     52 
---> 53         self.tagger = _mecab.Tagger(argument)
     54 
     55     def parse(self, sentence):

TypeError: pybind11::init(): factory function returned nullptr
```

<br>

그때는 다음과 같이 실행하고 진행하면 에러가 발생하지 않는다.
<br>

```bash
bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)
```

[관련된 깃허브 이슈](https://github.com/jonghwanhyeon/python-mecab-ko/issues/15)

<br>
